. ~/git-completion.bash
source ~/.git-prompt.sh
PS1="\[\033]0;\W\007\]";
export PS1+='\[\033[1;31m\]\W \[\033[0;36m\]$(__git_ps1 "(%s) ")\[\033[1;35m\]$\[\033[00m\] '
alias work='cd ~/Werk/'
alias stgit='git status'
alias sygit='git pull && git push'
alias cmgit='git commit -m'
alias server='python -m SimpleHTTPServer'

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi

# Always list all files colorized and trailing slash of directories and such
alias ls='ls -F ${colorflag}'

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias badge="tput bel"

# Change working directory to the top-most Finder window location
function cdf() { # short for `cdfinder`
	cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}

# Thanks @mathiasbynens
